# Generated by Django 3.1.4 on 2021-01-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210109_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, default=' ', max_length=250),
        ),
    ]
