# Generated by Django 3.1.4 on 2021-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210109_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=' ', help_text='Write the title of the article.', max_length=40),
        ),
    ]
