# Generated by Django 3.1.4 on 2021-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210110_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(default='posts/default.jpg', help_text='Choose the picture of the article.', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(default=' ', help_text='Write the text of the article.'),
        ),
    ]
