# Generated by Django 3.1.4 on 2021-01-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210112_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categoty',
            new_name='category',
        ),
    ]
